### ISSUE TITLE
regex dependency prevents vendorizing

### ISSUE THREAD

**Issue by olsonpm** [AlejandroFrias/case-conversion#18]
Just wanted to let you know that the regex dependency prevented me from vendorizing case-conversion (it's not purely python).  This isn't a big deal because I can fork and be on my way, but an alternative is to use python's `unicodedata`.  I replaced your regexes with the following functions and all your tests passed.  Granted, locally I cheated a little by replacing `regex.compile` with `re.compile` when searching for acronyms, but a function could wrap that logic as well.

** *I did not test for performance differences and I also understand you may prioritize having regex over case-conversion being vendorize'able*

<details>
<summary>
Click to reveal code
</summary>

```py
def _charIsSep(aChar):
    return (
        not _charIsUpper(aChar)
        and not _charIsLower(aChar)
        and not _charIsNumberDecimalDigit(aChar)
    )

# _isSep vs '^[^\p{Ll}\p{Lu}\p{Nd}]$'
def _isSep(aString):
    return len(aString) == 1 and _charIsSep(unicode(aString))


def _charIsNumberDecimalDigit(aChar):
    return unicodedata.category(aChar) == "Nd"


def _charIsLower(aChar):
    return unicodedata.category(aChar) == "Ll"


def _charIsUpper(aChar):
    return unicodedata.category(aChar) == "Lu"

# _isUpper vs '^[\p{Lu}]$'
def _isUpper(aString):
    return len(aString) == 1 and _charIsUpper(unicode(aString))

# _isValidAcronym vs '^[\p{Ll}\p{Lu}\p{Nd}]+$'
def _isValidAcronym(aString):
    if len(aString) == 0:
        return False

    for aChar in aString:
        if _charIsSep(unicode(aChar)):
            return False

    return True
```
</details>

**Comment by pykong** [comment]
@olsonpm Many thanks for your code samples. 
Indeed I'd like to make `case-conversion` dependency-free for better vendorizing. See #16 

Could you make a **PR** out of it, replacing the `regex` dependency with your code?

**Comment by olsonpm** [comment]
Yeah I can do that.  Thanks for the response

**Comment by pykong** [comment]
@olsonpm Great! Sorry for the late reply. 
`case-conversion` is now under active development again.

Note: Make it python 3 compatible, because as we all know py2 is EOL in 4 months

**Comment by pykong** [comment]
@olsonpm Have you started working on the **PR** if I may ask?
Reach out if you need any help in this regard.

**Comment by olsonpm** [comment]
i haven't.  If i don't find time this weekend then i'll close this issue because i don't know when i'll have time after that

**Comment by pykong** [comment]
Sure. Whatever suits you best.

**Comment by olsonpm** [comment]
I just raised pr #19 to solve this.  Because the environment was so slow to initialize with poetry I don't think I'll work on this further.

**Comment by pykong** [comment]
@olsonpm I am glad you found the time dor coding! Thank you very much.
Do not worry I will take over from here one. Sorry, for poetry causing you so much pain. I am possibly trimming down the `pyproject.toml` in the future to not impose my dev setup on other potential contributors.

Leave this issue open, it will be closed via merge.
